id: Arbitrary Text Injection

info:
  name: Arbitrary Text Injection
  author: Nikhil Kumar(https://www.linkedin.com/in/nikhil-kumar-4b9443166/)
  severity: Low
  tags:  injection

  
requests:
  - method: GET
    path:
      - "{{BaseURL}}/!!!ATENTION!!!_This_site_is_on_Maintenance_please_go_to_WWW.EVIL.COM"

    matchers:
      - type: word
        words:
          - "!!!ATENTION!!!_This_site_is_on_Maintenance_please_go_to_WWW.EVIL.COM"
        part: body

#Hackerone Report
#https://hackerone.com/reports/327671
