id: cve-2020-11710
info:
  name: Kong API Improper Authorization
  risk: Critical

params:
  - root: '{{.BaseURL}}'
  
variables:
  - endpoint: |
      status
requests: 
  - method: GET
    url: >-
      {{.root}}/{{.endpoint}}
    headers:
      - User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3984.0 Safari/537.36
    detections:
      - >-
        StatusCode() == 200 && (StringSearch("resBody", "kong_env") || StringSearch("resBody", "kong_db_cache_miss"))

references:
  - https://www.cvebase.com/cve/2020/11710
