id: Kronos wsdl found
info:
  name: Find Kronos wsdl exposure (Try XXE)
  author: Clark
  severity: medium
requests:
  - method: GET
    path:
      - "{{BaseURL}}/wfc/webservice/ReportConfigService?wsdl"
      - "{{BaseURL}}/wfc/XmlService"
      - "{{BaseURL}}/wfc/"

    matchers:
      - type: word
        words:
          - "xml-soap"
          - "application/xml"
        part: body
