id: login-field

info:
  name: Login Field Detection Template
  author: nithissh
  severity: info
  description: Searches Response body for input-tag and id= or name=
  tags: login,input

requests:
  - method: GET
    redirects: true
    # max-redirects is max number of redirects to follow. Can be blank.
    max-redirects: 1
    path:
      - "{{BaseURL}}/"
      - "{{BaseURL}}/login"
      - "{{BaseURL}}/admin"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'id="login"'
          - 'id="username"'
          - 'id="user"'
          - 'id="mail"'
          - 'id="email"'
          - 'name="login"'
          - 'name="username"'
          - 'name="user"'
          - 'name="mail"'
          - 'name="email"'
          - 'id="password"'
          - 'name="password"'
        condition: or

      - type: status
        status:
          - 200

      - type: word
        words:
          - '<input 
