id: CVE-2005-3344
info:
  name: Horde Groupware Unauthenticated Admin Access
  author:
  - l0ne1y
  description: "Debian Horde默认管理员空密码漏洞 \nHorde 是个以PHP为基础的架构，用于创建网络应用程序。\n\nHorde 3.0.4的默认安装包含具有空白密码的管理帐户，这可让远程攻击者获得访问权。 "
  severity: high
  remediation: |-
    官方修复方案：升级至最新软件版本
    https://www.horde.org/
    临时修复方案：<br/>1、建议系统管理人员将已发现的弱口令立即改成强口令，并拉网式排查所有系统管理员、用户、设备的弱口令，清扫未发现的弱口令。<br/>2、弱口令重在管理。企业应制定强口令制度（如：密码需包含大小写字母、数字、特殊字符至少三种格式，长度不少于十位，并且密码键盘排列无序，密码企业、个人信息无关联。<br/>3、弱口令排查方式可以通过汇总企业所有人员账户后根据强口令规则匹配自查、个性化制定字典暴力破解两种方式。<br/>4、推荐强口令在线生成:[https://suijimimashengcheng.51240.com/](https://suijimimashengcheng.51240.com/)<br/>5、推荐口令强度在线检测:[https://howsecureismypassword.net/](https://howsecureismypassword.net/)
requests:
- matchers:
  - type: word
    condition: and
    words:
    - '<title>Horde :: User Administration</title>'
  - type: status
    status:
    - 200
  matchers-condition: and
  path:
  - '{{BaseURL}}/horde/admin/user.php'
  - '{{BaseURL}}/admin/user.php'
  method: GET
  headers:
    Content-Type: text/html
