id: zippkin-unauth
info:
  name: zippkin unauth
  risk: High

params:
  - root: '{{.BaseURL}}'

requests:
  - method: GET
    redirect: false
    url: >-
      {{.root}}/config.json
    headers:
      - User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55
    detections:
      - >-
        StatusCode() == 200 && StringSearch("response", "{"environment"") && StringSearch("response", "defaultLookback") && StringSearch("resHeaders", "application/json")