id: Directory Content logs
info:
  name: Search for log.txt
  author: Clark
  severity: meduim
requests:
  - method: GET
    path:
      - "{{BaseURL}}/log/log.txt"
    matchers:
      - type: word
        words:
          - "log"
        part: body